### ISSUE TITLE
Load script template from user-provided file

### ISSUE THREAD

**Issue by Mencucci** [MarcoMeinardi/spwn#2]
Loading the script template from a user-provided configuration file would be a cool feature.

After a discussion on discord, a key issue came up: the libc vs. no libc template differences.

https://github.com/MarcoMeinardi/spwn/blob/655c4b6d1b91a1821df35b5918da1b22d91f551d/spwn/scripter.py#L9

In the current template, the line above is hard to remove in case a libc is not present.

The following workarounds were proposed:

- double nested format string
- explicitly handling `FileNotFoundError`
- aggregated token, [pwninit style](https://github.com/io12/pwninit/blob/dc024f3f2889b540e1882ba50a5aeaf9f9975ec4/src/template.py#L5)

None of them was deemed in line with the style goals of this project.

Suggested labels: enhanchement, feature request

**Comment by MarcoMeinardi** [comment]
The user-provided template has been introduced in [this commit](https://github.com/MarcoMeinardi/spwn/commit/d98458fd4711f317a29d73590018b23daec7f36d) and slightly improved later.

The workaround I came up with is to have a unique template that includes libc and, in `Scripter::create_script`, remove every line that contains `{libc}`, if no libc is provided (see [this](https://github.com/MarcoMeinardi/spwn/blob/15c2057317a98bf51e016234fe7e7679cd7fef10/spwn/scripter.py#L28)).
